import type {
	PluginContext,
	PluginInfo,
} from '../../packages/server/src/plugins/plugin.interface.js';

export default class ExampleInfoPlugin {
	private context!: PluginContext;

	async onLoad(context: PluginContext): Promise<void> {
		this.context = context;

		// Register an API endpoint (server-side only)
		context.api.registerEndpoint({
			methodName: 'getMovieTrivia',
			method: 'GET',
			path: '/trivia/:movieId',
			handler: async ({ params }) => {
				const movie = (await context.getMovieById(params.movieId)) as {
					title?: string;
				} | null;
				return {
					facts: [
						`"${movie?.title ?? 'Unknown'}" is in your library!`,
						'This trivia was generated by the example-info plugin.',
					],
				};
			},
			schema: {
				params: { movieId: 'string' },
				response: { facts: {} },
			},
		});

		context.logger.log('Example Info plugin loaded (server)');
	}

	async onUnload(): Promise<void> {
		this.context.logger.log('Example Info plugin unloaded');
	}

	getInfo(): PluginInfo {
		return {
			name: 'example-info',
			displayName: 'Example Info',
			version: '1.0.0',
			description: 'Example plugin demonstrating API endpoint and UI slot registration',
			author: 'Mu',
			enabled: true,
			loaded: true,
			status: 'enabled',
			permissions: ['read:movies', 'cache'],
		};
	}

	async onInstall(context: PluginContext): Promise<void> {
		context.logger.log('Example Info plugin installed');
	}

	async onUninstall(context: PluginContext): Promise<void> {
		context.logger.log('Example Info plugin uninstalled');
	}

	async onEnable(context: PluginContext): Promise<void> {
		context.logger.log('Example Info plugin enabled');
	}

	async onDisable(context: PluginContext): Promise<void> {
		context.logger.log('Example Info plugin disabled');
	}
}
